!path = expand_path('+/Users/jama6159/IDLWorkspace84/Default') + path_sep(/SEARCH_PATH) + !path
!path = expand_path('+/Users/jama6159/IDLWorkspace84/Research') + path_sep(/SEARCH_PATH) + !path
!path = expand_path('+/Users/jama6159/IDLWorkspace84/Coyote') + path_sep(/SEARCH_PATH) + !path
!path = expand_path('+/Users/jama6159/IDLWorkspace84/Woods IDL Library') + path_sep(/SEARCH_PATH) + !path
!path = expand_path('+/Users/jama6159/Drive/CubeSat/MinXSS Server/9000 Processing/code') + path_sep(/SEARCH_PATH) + !path
;!path = expand_path('+/Users/jmason86/Dropbox/Development/IDLWorkspace84/Default') + path_sep(/SEARCH_PATH) + !path
;!path = expand_path('+/Users/jmason86/Dropbox/Development/IDLWorkspace84/Research') + path_sep(/SEARCH_PATH) + !path
;!path = expand_path('+/Users/jmason86/Dropbox/Development/IDLWorkspace84/CubeSat') + path_sep(/SEARCH_PATH) + !path
;!path = expand_path('+/Users/jmason86/Dropbox/Development/IDLWorkspace84/Coyote') + path_sep(/SEARCH_PATH) + !path
;!path = expand_path('+/Users/jmason86/Drive/CubeSat/MinXSS Server/9000 Processing/code') + path_sep(/SEARCH_PATH) + !path